name: Check

on:
  pull_request:
    branches:
      - main
  merge_group:
    branches:
      - main

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        with:
          node-version: 18.18.2
          cache: pnpm
      - run: pnpm install
      - run: pnpm run lint:prettier
      - run: pnpm run lint:eslint

  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        with:
          node-version: 18.18.2
          cache: pnpm
      - run: pnpm install
      - run: pnpm run codegen
      - run: pnpm run typecheck

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        with:
          node-version: 18.18.2
          cache: pnpm
      - run: pnpm install
      - run: pnpm run codegen
      - run: pnpm run test
