name: Check

on:
  pull_request:
    branches:
      - main
  merge_group:
    branches:
      - main

jobs:
  validate-graphql-queries:
    name: Validate GraphQL Queries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@bea5baf987ba7aa777a8a0b4ace377a21c45c381 # v3
        with:
          node-version: 18
          cache: pnpm
      - run: pnpm install
      - run: pnpm run schema:validate --output ./.inspector-validate-report.json

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@bea5baf987ba7aa777a8a0b4ace377a21c45c381 # v3
        with:
          node-version: 18
          cache: pnpm
      - run: pnpm install
      - run: pnpm run lint:eslint --format json --output-file .eslint-report.json
      - name: Annotate ESLint results
        uses: ataylorme/eslint-annotate-action@v2
        if: failure()
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          report-json: ".eslint-report.json"

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@bea5baf987ba7aa777a8a0b4ace377a21c45c381 # v3
        with:
          node-version: 18
          cache: pnpm
      - run: pnpm install
      - run: pnpm run lint:prettier

  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@bea5baf987ba7aa777a8a0b4ace377a21c45c381 # v3
        with:
          node-version: 18
          cache: pnpm
      - run: pnpm install
      - run: pnpm run codegen
      - run: pnpm run typecheck
