name: Check GraphQL Schema

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

jobs:
  diff:
    name: Diff schema
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: kamilkisiela/graphql-inspector@v3.4.0
        with:
          schema: "schema.graphql"
          endpoint: "${{ secrets.GRAPHQL_API_ENDPOINT }}"

  validate:
    name: Validate queries
    runs-on: ubuntu-latest
    needs:
      - diff
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - run: pnpm add --global @graphql-inspector/ci @graphql-inspector/validate-command
      - run: graphql-inspector validate "./src/**/*.{ts,tsx}" ./schema.graphql
