name: Check GraphQL Schema

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: kamilkisiela/graphql-inspector@v3.4.0
        with:
          schema: "schema.graphql"
          endpoint: "${{ secrets.GRAPHQL_API_ENDPOINT }}"
