name: Check GraphQL Schema

on:
  push:
    branches:
      - "main"
  schedule:
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  diff:
    name: Diff GraphQL Schema
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: kamilkisiela/graphql-inspector@v3.4.0
        with:
          schema: "schema.graphql"
          endpoint: "${{ vars.GRAPHQL_API_ENDPOINT }}"

  update:
    name: Update GraphQL Schema
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - run: pnpm install
      - run: pnpm run schema:introspect $GRAPHQL_API_ENDPOINT
        env:
          GRAPHQL_API_ENDPOINT: "${{ vars.GRAPHQL_API_ENDPOINT }}"
      - uses: peter-evans/create-pull-request@v5
        with:
          token: "${{ secrets.UPDATE_SCHEMA_GITHUB_TOKEN }}"
          title: "chore(schema): Update `graphql.schema`"
          commit-message: "chore(schema): Update `graphql.schema`"
          branch: chore/update-graphql-schema
          delete-branch: true
